---
name: CGI-Application-Plugin-ValidateQuery
version: v1.0.3
author:
  - 'Nathaniel K Smith <nate@summersault.com>'
abstract: lightweight query validation for CGI::Application
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  CGI::Application: 3.31
  Test::More: 0
requires:
  Params::Validate: 0
configure_requires:
  Module::Build: 0.35
provides:
  CGI::Application::Plugin::ValidateQuery:
    file: lib/CGI/Application/Plugin/ValidateQuery.pm
    version: v1.0.3
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
